# Generated by Django 5.1.7 on 2025-03-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('education_level', models.IntegerField(null=True)),
            ],
        ),
    ]
